[theme]
base                     = "light"
primaryColor             = "#008b74"
backgroundColor          = "#f0fdfb"
secondaryBackgroundColor = "#008b74"
textColor                = "#002b22"
font                     = "sans serif"
 
[client]
showSidebarNavigation = true
toolbarMode = "viewer"
 
[browser]
gatherUsageStats = false
