[theme]
base                     = "light"
primaryColor             = "#00c9a7"
backgroundColor          = "#f0fdf9"
secondaryBackgroundColor = "#00b396"
textColor                = "#0d2b25"
font                     = "sans serif"
 
[client]
showSidebarNavigation = true
toolbarMode = "viewer"
 
[browser]
gatherUsageStats = false
